// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail loudly in the console (not with a white screen) if env is misconfigured.
// The contact form surfaces its own user-facing error on insert failure.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "Supabase env missing: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY. The contact form will not submit."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// No auth/login in this app — it's a public contact form only, so skip session
// persistence (avoids needless localStorage writes and token refresh timers).
export const supabase = createClient<Database>(
  SUPABASE_URL ?? "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY ?? "placeholder-anon-key",
  { auth: { persistSession: false, autoRefreshToken: false } }
);